import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationHeader } from "@/components/Header";
import { UserProvider } from "@/components/Context/UserContext";
import { Toaster } from "@/components/ui/toaster";
import { CartProvider } from "@/components/Context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <CartProvider>
            <NavigationHeader />
            {children}
          </CartProvider>
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
